### ISSUE TITLE
Donner aux clients la possibilité de changer ça réservation

### ISSUE THREAD

**Issue by senzowayne** [senzowayne/resavo#11]
Il devrait être possible pour un client de modifier sa reservation au moins 2 fois tant qu'il est bien 48h avant la réservation.

**Comment by pierreminiggio** [comment]
Je ne sais pas comment tu comptes dev' ça, mais prévoir que la valeur qui permet de définir que le délai soit 48h soit lié à la réservation si jamais plus tard tu veux que ce soit une valeur paramétrable par les utilisateurs.

**Comment by ImenRad** [comment]
Je m'occupe de cette issue.
