### ISSUE TITLE
Supprimer l'utilisation de CDN 

### ISSUE THREAD

**Issue by senzowayne** [senzowayne/resavo#23]
Pour une optimisation maximale, remplacer tout les links CDN par les fichiers nécessaire au bon fonctionnement de l'application

**Comment by instantech** [comment]
C'est tout à fait le contraire. Mieux vaut un cdn, parceque les navigateurs sont supers intélligents pour mettre en caches les fichiers en provenance depuis d'un cdn. Ce qui permet un gain performance
