### ISSUE TITLE
Remplacer variable global telle que $_POST par les methodes object de la request

### ISSUE THREAD

**Issue by senzowayne** [senzowayne/resavo#26]
L'idée est de remplacer tout le code appelant les variables POST 
en utilisant l'object request.

Cf: https://symfony.com/doc/current/components/http_foundation.html

**Comment by victorfau** [comment]
Je peux le faire demain soir, par contre je commence à me familiariser avec le projet, et lors de l'enregistrement d'une réservation, j'ai l'impression que ça tourne en rond. Est ce que je suis le seul à qui cela arrive.

**Comment by senzowayne** [comment]
Super bien vu, c'est vrai ça mouline un peu mais ça doit quand même arrivé au bout normalement.
enfaite si tu veux j'ai un peu bidouiller dans le JS avec des setTimeout mais c'est pas top du tout.. sans doute ça qui fait que ça mouline.. j'vais refaire un pti test je reviens vers toi

**Comment by senzowayne** [comment]
@victorfau effectivement sur la méthode verifPaiement il récupère null fix ça 😉

**Comment by senzowayne** [comment]
@victorfau fait un pti git pull sur le master ca devrait être résolu la (regarde bien dans le .env que ta encore t'es identifiants paypal)

**Comment by victorfau** [comment]
okdac de mon coté je réglerai l'issue mia je vais t'attendre pour pouvoir tester.

**Comment by victorfau** [comment]
hello @senzowayne 

L'issue est completer, par contre je n'arrive pas a push la branche.

**Comment by senzowayne** [comment]
Essaie de sauvegarder ton travail à coter essaie de recloner le projet mais cette fois en mettant 
`git clone git@github.com:USERNAME/resavo.git`

**Comment by pierreminiggio** [comment]
Pour éviter les setTimeout. essaie d'utiliser des callbacks ou des promesses.
Vaut mieux se débarrasser des setTimeout le plus tôt possible. J'en ai déjà fait les frais sur un projet xD

**Comment by senzowayne** [comment]
Carrément d’accord avec toi ! C’est du bricolage 😂
