### ISSUE TITLE
Question / Suggestion d'évolution - Connexion avec Google Agenda

### ISSUE THREAD

**Issue by pierreminiggio** [senzowayne/resavo#28]
Salut! J'ai remarqué dans le Readme que y'a des identifiants Paypal à indiquer pour les paiements, mais j'vois rien pour lier à d'autres agendas style google agenda.

Côté Laravel j'sais qu'on a des packages pour faire le lien facilement avec l'API de google agenda. Mais j'suppose que côté Symfony doit déjà y avoir des trucs tout fait aussi.

**Comment by senzowayne** [comment]
Super suggestion merci ça serai à mettre en place effectivement 😉

**Comment by Dev-Int** [comment]
Comme proposé dans cet article : https://hugo-soltys.com/blog/easily-implement-google-login-with-symfony-4
Juste vérifier le suivi du bundle de knp. Ils ne sont pas tous à jour.

**Comment by senzowayne** [comment]
Top bien vu

**Comment by senzowayne** [comment]
#105
