### ISSUE TITLE
Mise en place du composant Workflow

### ISSUE THREAD

**Issue by senzowayne** [senzowayne/resavo#3]
Workflow permet la gestion du statue d'une réservation

Il serai intéressant d’utiliser cette outils pour gérer différent état d’une réservation

Cf: https://symfony.com/doc/4.4/components/workflow.html
**Note: étudier les cas possible**

**Comment by Dev-Int** [comment]
Article intéressant lors du calendrier de l'Avent de l'Afsy : [Développer votre application autour du composant Workflow](https://afsy.fr/avent/2019/12-workflow-as-middleware)
