### ISSUE TITLE
Création d'un entity Config

### ISSUE THREAD

**Issue by senzowayne** [senzowayne/resavo#32]
L'idée serai de pouvoir personnaliser sa config de façon dynamique, on y retrouverai les choix suivants :
- Paiement (ex : Paypal ou Stripe)
- Couleur du thème 
- Nom de l'enseigne

[EN COUR DE REDACTION]

**Comment by willice93** [comment]
certaines variables sont nécessaires selon le secteur d'activités  . Pour rendre le système de réservation adaptable a toutes les professionnels qui en aurait besoin on a besoin par exemple 

		#pour un salon de coiffure 

nb de siege(coiffeur equivalent a une salle )
durée d'une seance (relation a un type de prestation)
type de prestation (nom du service et durée )

activité similaires
# barbershop
#pose de cils 
#pose d'ongle 
#sallon de soins esthetique 

	#pour un salon de massage

nb de salles 
durée d'une séance (relation a un type de prestation)
type de prestation (nom du service et durée )

activité similaires	
	#un spa
	#un salle des fêtes 
	# un hôtel 
Toutes ces donnés doivent donc être demandées aux professionnel et modifiable atravers le panneau d'administration
