### ISSUE TITLE
Scinder le projet en deux : une API pour gerer le backend et le frontend à part

### ISSUE THREAD

**Issue by faso-dev** [senzowayne/resavo#35]
L'API sera chargé de gerer le backend, tandisque le frontend va se charger de l'experience utilisateur. Ça permet d'avoir un code beaucoup plus lisible et facilement maintenable.

**Comment by victorfau** [comment]
Je suis d'accord sur le principe mais faire ça va demander pas mal de modifs, je me questionne sur le rapport temps/intérêt. 
Tu en penses quoi ?

**Comment by instantech** [comment]
@victorfau Je me dis qu'avec une api, nous serons plus autonome. Nous pouvous faire une appli mobile, desktop, tout ce que l'on veut car on aura les donnée totalement déconnecté du front.
Mieux vaut partire sur des bonnes bases pendant que le projet est encore pétit que quant il sera a un stade ou on ne peut plus faire du refactoring.

Concernant le temps, l'écosystem de symfony est tellement riche d'outils. Tiens pour l'API, on peut utiliser API PLATEFORM pour gagnger plus de temps.

**Comment by senzowayne** [comment]
Je pense que tu as raison du coup on repartirai d'un core API platform directement en vrai on repart de zéro du coup (bien qu'il n'y pas grand chose)

**Comment by pierreminiggio** [comment]
Si vous faites ça, je pense que ça serait cohérent de découper le projet en plusieurs repos, un front, un back. Comme ça si quelqu'un veut par exemple réutiliser l'API et faire son propre front il pourra.

**Comment by senzowayne** [comment]
L'idée me bot vachement vous connaissez des contributeurs qui serai chaud nous faire une base pour le front ? Du coup on partirai sur l'idée de symfony 4.4 + API et le front en React si tous le monde approuve on fonce ! :) Cc @Pierstoval si ta des suggestions aussi n'hésite pas 😉

**Comment by senzowayne** [comment]
Préparation de l'API #48
