### ISSUE TITLE
Faire un debriefing du projet 

### ISSUE THREAD

**Issue by faso-dev** [senzowayne/resavo#36]
Pour que nous puissions avancer tous dans des bonnes directions, je suggères que l'on fasse un debriefing du projet. Expliquer le but du projet, comment le réaliser, les différents acteurs, la conception(base de donnée + relation)

**Comment by senzowayne** [comment]
Le but du projet c'est de couvrir un maximum de "use case" dans l'idée j'imagine une config à faire à l'installation du projet pour définir le type de merchant qui utilisera le système, ensuite selon le merchant on rentrerai dans les différentes conditions défini. Pas assez de recul mais je vois pas grand chose qui diffèrent.. (Au premier abord je vois déjà une différence entre ceux qui proposent des salles et ceux qui proposent des services)
exemple : un spa privatif tu reserve une salle 
une coiffeuse tu reserve une prestation

Sinon l'idée des séances et de la date reste la même approche.

Niveau conception je pense que la base installé devrait répondre au besoin sauf si vous avez des suggestion hésitez surtout pas on le construit ensemble ce projet 😉

**Comment by pierreminiggio** [comment]
La différence technique entre une salle et une prestation, c'est juste le nombre de place au finale.
Une prestation c'est rien de plus qu'une salle avec une seule place.
