### ISSUE TITLE
Séparer l'affichage des données

### ISSUE THREAD

**Issue by pierreminiggio** [senzowayne/resavo#42]
Bonne pratique de code : 
De la même façon que tu veux séparer les contrôleurs des vues, tu voudras toujours séparer ton template de mail des données que tu lui donnes.
ça te permettra de réutiliser ton template.

![image](https://user-images.githubusercontent.com/35456349/72014894-0d9f9480-3261-11ea-93fa-a889bab32d4a.png)

D'ailleurs, utiliser un templater comme twig pour les mails, faut les traiter comme n'importe quelle autre vue.

**Comment by senzowayne** [comment]
c'est fait dans #50 je ferme l'issue 😉
