### ISSUE TITLE
Docker compose [php]

### ISSUE THREAD

**Issue by senzowayne** [senzowayne/resavo#83]
Lors d'un docker-compose up, php effectue quelques tâches au démarrage pendant ce temps on obtient une 500 qui peut laisser penser que rien ne fonctionne. 

Trouvez un moyen d'informer ou d'éviter l'erreur 500.

**Comment by yalefresne** [comment]
Ça m'intéresse d'effectuer les recherches sur ce soucis.

**Comment by senzowayne** [comment]
Au top avec grand plaisir !

**Comment by yalefresne** [comment]
I'm on it ! ;)

**Comment by yalefresne** [comment]
En j'ai un soucis de memory-limit à la première commande `composer install` ^^ j'ai créé une issue #84 pour utiliser une image docker pour Composer et Node par la même occasion.

**Comment by senzowayne** [comment]
Ah je l'ai jamais eu pour ma part. Mais effectivement si ta constatée l'erreur c'est cool du coup on peut le régler 😉

**Comment by yalefresne** [comment]
Je pense que l'on peut clore cette issue, car la PR #89 a dû résoudre le soucis ? En tout cas je n'ai pas rencontré d'erreur 500 au moment du `docker-compose up`.

**Comment by senzowayne** [comment]
Encore une fois bien joué 👌🏽 ça marche niquel !
