### ISSUE TITLE
Question/Suggestion - Utiliser des images Docker pour Composer et Node

### ISSUE THREAD

**Issue by yalefresne** [senzowayne/resavo#84]
Je pense que ça pourrait être bien d'utiliser aussi des images Docker pour composer et node, afin d'avoir tout l'environnement dans docker.

Qu'en penses tu @senzowayne ?

**Comment by senzowayne** [comment]
Ah oui je vois en gros qu'on puisse arriver sur une machine installer docker uniquement et de dépendre de rien d'autre..?
Superbe idée !

**Comment by yalefresne** [comment]
Yes, comme ça tout le monde utilise les mêmes versions de tous les outils du projet.
