### ISSUE TITLE
Question/Suggestion - Executer toutes les commandes du Makefile dans des containers Docker

### ISSUE THREAD

**Issue by yalefresne** [senzowayne/resavo#85]
J'ai remarqué que certaines commande du Makefile ne sont pas executer dans les containers Docker, par exemple celle-ci:
https://github.com/senzowayne/resavo/blob/a8057a7ad91f069108f7bb565c9a4a312fdfbab6/Makefile#L26

**Comment by senzowayne** [comment]
Oui c'était volontaire de ma part, car un cache clear dans contenaire était beaucoup plus long qu'en dehors mais c'est vrai que si on suit ta suggestions issue #84 ça ne tiens plus la route faut tout faire dans les contenaires

**Comment by yalefresne** [comment]
J'ai mis `cache:clear` en exemple mais c'est plus quand j'ai vu les lignes suivantes que je me suis posé la question.
https://github.com/senzowayne/resavo/blob/a8057a7ad91f069108f7bb565c9a4a312fdfbab6/Makefile#L35
https://github.com/senzowayne/resavo/blob/a8057a7ad91f069108f7bb565c9a4a312fdfbab6/Makefile#L38
Je trouve ça plus cohérent d'utiliser les containers, ne serait-ce que pour utiliser la même version de l'outil.
Après rien n’empêche les développeurs de jouer la commande hors du container.

**Comment by senzowayne** [comment]
Je fais les modifications ou t'es déjà dessus ?

**Comment by yalefresne** [comment]
Je ne suis pas dessus, mais je peux m'en occuper, surtout si je m'occupe de rajouter des containers pour Composer et Node je rajouterais les commandes lié dans le Makefile.  
Je ne sais pas comment tu veux procéder.
